main: com.github.xenon.survival.TeamSurvivalPlugin
version: 1.0
name: Survival
api-version: 1.16
depend: [Kotlin, ProtocolLib]
commands:
  svl:
    permission: op
    description: command for team-survival